#!/usr/bin/env python3
"""d_nonnormal_thermo_price_of_amplification_probe.py -- BREAKTHROUGH-HUNT (D-hands, foreground). HYPOTHESIS for D's QC. No commits.

QUESTION (ties the sigma_min FRAME to the thermodynamic COST). D1-bridge found: on a NON-NORMAL transfer
operator the STATIONARY fluctuation is governed by the PSEUDOSPECTRAL sigma_min (distance-to-instability in
resolvent norm), NOT the eigenvalue gap -- amplified by (gap/sigma_min_pseudo)^2 (D1: 4.142x -> 17.2x). Does that
fluctuation amplification have a THERMODYNAMIC DUAL = EXCESS DISSIPATION? Does a non-normal transfer cost more
WORK (over the reversible/equilibrium floor), and is that excess governed by the same pseudospectral sigma_min?

TESTBED (the STOCHASTIC-SIBLING frame the D1 memory established): linear overdamped Langevin / OU process
    dx = A x dt + sqrt(2 D) dW ,   D = I (isotropic noise = the observer's default metric)
Stationary covariance Sigma solves the LYAPUNOV eq  A Sigma + Sigma A^T = -2 D. Two observables:
    FLUCTUATION:  Var = trace(Sigma)                                    (the D1 amplified quantity)
    DISSIPATION:  Ep   = steady-state entropy-production rate = Tr[Omega^T D^-1 Omega Sigma],
                  Omega = A + D Sigma^-1  (local mean velocity nu(x)=Omega x; all NESS heat is dissipation, dF=0)
The KNOB is NON-NORMALITY at FIXED spectrum: A = V Lambda V^-1, Lambda fixed, V = I + g*N (N strictly upper) ->
eigenvalues EXACTLY Lambda, non-normality (||A||/rho, dep(A), gap/sigma_min) grows with g. The REVERSIBLE FLOOR
is the NORMAL operator with the SAME spectrum (real spectrum -> symmetric A -> equilibrium -> Ep = 0 exactly).

PRE-REGISTERED (code before numbers; BOTH directions; thresholds FROZEN in PRE):
  C  (QUALITATIVE law): non-normality has a POSITIVE thermodynamic price whose GOVERNOR is the pseudospectral
     sigma_min -- the SAME governor as the fluctuation. Concretely: (i) Ep(symmetric,same spectrum)=0 (floor);
     (ii) Ep(g)>0 rises monotonically with non-normality; (iii) the exponent of Ep vs (gap/sigma_min) MATCHES the
     exponent of the excess variance dVar vs (gap/sigma_min) (they co-track), across the instance-space; (iv) it
     does NOT track the Kreiss constant (the transient governor) -- the cost is a sigma_min phenomenon, not a
     transient one. Over-determined: closed-form Ep == DIRECT Sekimoto-heat Langevin simulation.
  notC (any): Ep does not rise with non-normality at fixed spectrum (amplification is variance-only, NO energy
     price -- "info, not energy"); OR Ep tracks Kreiss/transient not sigma_min; OR the exponents do not co-track.
  ANTI-HYPE BOUND (pre-registered as FALSE, forced): the price is NOT numerically "= the amplification factor".
     The clean 2x2 identity Ep == dVar (=g^2/2) is a UNITS COINCIDENCE: it breaks under time-rescaling A->c*A
     (Ep is a RATE ~c, Var ~1/c, so Ep/dVar ~ c^2). So "17.2x amplification => 17.2x dissipation" is FALSE;
     only the pseudospectral GOVERNOR and the co-tracking EXPONENT are universal, the prefactor is model-specific
     (consistent with the D1 memory: Var~sigma_min^-p has model-specific p in {1.2..2.4}, NOT a universal -2).

FORCED ADVERSARIES (each to its strongest fair form via OODA):
  ADV-tautology (leaning-positive): "Ep and Var both come from the same Sigma, so co-scaling is trivial." FORCED:
     measure Ep INDEPENDENTLY by direct Langevin simulation of the Sekimoto heat rate <(Ax) o dx>/dt (touches NO
     Sigma); over-determine vs closed form. + pseudospectral sigma_min from the resolvent (independent of Sigma).
  ADV-rotation (confound): "cost is from complex-eigenvalue ROTATION, not non-normality." FORCED: FIX the spectrum
     and vary ONLY non-normality; ALSO a complex-spectrum control where the NORMAL rotation baseline dissipates
     >0 yet does NOT amplify variance -> the EXCESS (non-normal - normal) is what tracks the variance excess.
  ADV-Kreiss (ORIENT if excess != factor): "the governor is really the Kreiss constant / transient, not sigma_min."
     FORCED: measure the Kreiss exponent per family; if Ep co-wanders with the (model-specific) variance sigma_min
     exponent and NOT with Kreiss, the governor is pseudospectral sigma_min.
  ADV-honest-neg ("info not energy"): REFUTED only if Ep>0 is robust (not a noise-metric artifact). GEOMETRIC read:
     both Var-amplification and Ep are generated by the SINGLE antisymmetric current matrix Q = A Sigma + D; Q=0
     <=> A normal-in-the-noise-metric <=> equilibrium <=> Ep=0 AND no anomalous amplification. Same source.

ANCHORS (external, never a tautology gate): pseudospectra sigma_min(A-i w I) (Trefethen-Embree 2005);
  Harada-Sasa equality (2005) dissipation = integrated FDT-violation -> here FDT holds (Ep=0) for symmetric and
  is violated PROPORTIONAL TO Q for non-normal (structural anchor, verified); 2x2 CLOSED FORM Ep=g^2/2 derived by
  hand. kT_eff = 1 (star1 units, consistent with the D non-eq rig d_noneq_jarzynski_crooks_tur_certwork.py).

Run: cd . && OMP_NUM_THREADS=4 nice -n 10 \
     python3 \
     d_nonnormal_thermo_price_of_amplification_probe.py
Evidence: artifacts/d_nonnormal_thermo_price_of_amplification_evidence.json  (CPU, seconds; no commit)
"""
import os, sys, json, math
for _v in ("OMP_NUM_THREADS", "OPENBLAS_NUM_THREADS", "MKL_NUM_THREADS"):
    os.environ.setdefault(_v, "4")
import numpy as np
from scipy.linalg import solve_lyapunov, svdvals, expm

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(os.path.dirname(HERE))
OUT = os.path.join(HERE, "artifacts", "d_nonnormal_thermo_price_of_amplification_evidence.json")

PRE = dict(
    # ---- 2x2 analytic anchor + over-determination ----
    A_analytic_relerr      = 1e-9,   # closed-form Ep == hand-derived g^2/2 (2x2, both eigenvalues -1)
    A_sim_relerr           = 0.04,   # DIRECT Sekimoto-heat Langevin sim == closed-form Ep (independent of Sigma)
    A_floor_zero           = 1e-10,  # Ep(symmetric same spectrum) == 0 (reversible/equilibrium floor)
    A_EpEqVar_2x2          = 1e-9,   # in the 2x2 defective case Ep == dVar EXACTLY (the clean-but-coincidental identity)
    # ---- the ANTI-HYPE bound: Ep==dVar is a units coincidence (breaks under time-rescale) ----
    C3_rescale_ratio_min   = 3.0,    # Ep/dVar max/min across A->c*A (c in {0.5,1,2}) >= this (a real identity would be ~1)
    C3_rescale_slope       = (1.7, 2.3),  # d ln(Ep/dVar)/d ln c == 2 (rate/variance dimensional signature)
    # ---- fixed-spectrum non-normality sweep ----
    B_floor_zero           = 1e-9,   # Ep(g=0, normal) == 0
    B_monotone             = True,   # Ep(g) strictly increasing in non-normality
    B_exponent_match_tol   = 0.30,   # |p_Ep - p_dVar| (vs gap/sigma_min) small: dissipation & variance co-track
    B_kreiss_decoupled     = 2.0,    # over the sweep Ep grows >= this-x MORE than Kreiss (Ep is NOT the transient)
    # ---- instance space: exponents co-wander (sigma_min governor), NOT pinned to Kreiss ----
    D_min_instances        = 20,
    D_exp_match_med_tol     = 0.35,  # median |p_Ep - p_dVar| across families: co-track
    D_exp_wander_min        = 0.40,  # p_dVar must WANDER across families by >= this (model-specific, not universal-2)
    D_kreiss_mismatch_min   = 0.30,  # median |p_Ep - p_Kreiss| >= this (Ep does not follow Kreiss)
    # ---- rotation control ----
    C1_normal_rot_dissipates = 1e-3, # normal complex-spectrum (rotation) has Ep>0 WITHOUT variance amplification
    C1_excess_tracks         = 0.35, # the NON-NORMAL excess exponent still matches the variance-excess exponent
    SEED = 20260705,
)


# ============================================================ core linear-OU thermodynamics
def lyap_sigma(A, D):
    return solve_lyapunov(A, -2.0 * D)                       # A S + S A^T = -2 D

def ep_rate(A, Sigma, D):
    """steady-state entropy-production rate = Tr[Omega^T D^-1 Omega Sigma], Omega = A + D Sigma^-1 (local mean vel)."""
    Si = np.linalg.inv(Sigma); Di = np.linalg.inv(D)
    Om = A + D @ Si
    return float(np.trace(Om.T @ Di @ Om @ Sigma))

def ep_rate_Q(A, Sigma, D):
    """independent closed form via the antisymmetric probability-current matrix Q = A Sigma + D (Q=0 <=> equilibrium)."""
    Q = A @ Sigma + D
    Si = np.linalg.inv(Sigma); Di = np.linalg.inv(D)
    return float(np.trace(Di @ Q @ Si @ Q.T)), Q

def pseudo_sigmin(A, ngrid=2001):
    """pseudospectral distance-to-instability = min_w sigma_min(i w I - A)  (Trefethen-Embree)."""
    n = A.shape[0]; ev = np.linalg.eigvals(A)
    wmax = 2.0 * (1.0 + float(np.max(np.abs(ev.imag))))
    ws = np.linspace(-wmax, wmax, ngrid); I = np.eye(n)
    best = np.inf
    for w in ws:
        s = svdvals(1j * w * I - A)[-1]
        if s < best: best = s
    return float(best)

def kreiss_const(A, ne=140, no=161):
    """Kreiss constant K = sup_{Re z>0} Re(z) ||(z I - A)^-1||  (the transient/tier-3 governor). K>=1 always;
       a fine geometric grid near the spectrum is needed (else K undershoots 1)."""
    n = A.shape[0]; ev = np.linalg.eigvals(A)
    emax = 2.0 * (1.0 + float(np.max(np.abs(ev.real)))); wmax = 2.0 * (1.0 + float(np.max(np.abs(ev.imag))))
    etas = np.concatenate([np.geomspace(1e-3, 0.2, ne // 2), np.linspace(0.2, emax, ne - ne // 2)])
    oms = np.linspace(-wmax, wmax, no); I = np.eye(n); K = 0.0
    for e in etas:
        for w in oms:
            K = max(K, e * np.linalg.norm(np.linalg.inv((e + 1j * w) * I - A), 2))
    return float(K)

def transient_gmax(A, nt=400, tmax=None):
    """actual transient growth G_max = sup_{t>=0} ||e^{At}||_2 (the tier-3 transient the abscissa/Kreiss bound)."""
    ev = np.linalg.eigvals(A); tmax = tmax if tmax else 8.0 / max(-np.max(ev.real), 1e-3)
    return float(max(np.linalg.norm(expm(A * t), 2) for t in np.linspace(0.0, tmax, nt)))

def sim_ep_sekimoto(A, D, rng, dt=1e-3, nsteps=80000, n=4000, burn=15000):
    """INDEPENDENT Ep: direct overdamped-Langevin sim, Sekimoto heat rate dQ = f o dx (Stratonovich), f = A x.
       Steady-state <dQ>/dt = entropy-production rate. Uses NO Sigma -> breaks the 'both from Sigma' tautology."""
    nn = A.shape[0]; L = np.linalg.cholesky(2.0 * D); sq = math.sqrt(dt)
    x = rng.standard_normal((n, nn)); acc = 0.0; cnt = 0
    for k in range(nsteps):
        f0 = x @ A.T
        dxi = f0 * dt + (rng.standard_normal((n, nn)) @ L.T) * sq
        xnew = x + dxi
        f1 = xnew @ A.T
        dQ = np.sum(0.5 * (f0 + f1) * dxi, axis=1)           # Stratonovich midpoint force . displacement
        if k >= burn: acc += dQ.mean(); cnt += 1
        x = xnew
    return acc / cnt / dt

def make_A(lam, Nmat, g):
    V = np.eye(len(lam)) + g * Nmat
    return V @ np.diag(lam) @ np.linalg.inv(V)               # eigenvalues EXACTLY lam; non-normality grows with g

def normal_ref_var(lam):
    """Var of the NORMAL operator with the same (real) spectrum = symmetric A = equilibrium floor: sum 1/|lam_i|."""
    return float(np.sum(1.0 / np.abs(np.real(lam))))

def slope(x, y):
    x = np.asarray(x, float); y = np.asarray(y, float)
    return float(np.polyfit(np.log(x), np.log(y), 1)[0])


# ============================================================ PART A -- 2x2 analytic anchor + over-determination
def part_A(rng):
    D = np.eye(2); rows = []
    for g in [0.0, 0.5, 1.0, 2.0, 4.0]:
        A = np.array([[-1.0, g], [0.0, -1.0]])               # eigenvalues both -1 (defective Jordan-near); gap=1
        S = lyap_sigma(A, D); var = float(np.trace(S))
        epO = ep_rate(A, S, D); epQ, Q = ep_rate_Q(A, S, D)
        ep_analytic = g * g / 2.0                            # HAND-DERIVED closed form (see docstring)
        dvar = var - 2.0                                     # dVar over symmetric floor (Var_norm = 2)
        sm = pseudo_sigmin(A); amp = (1.0 / sm) ** 2         # gap=1
        eps = sim_ep_sekimoto(A, D, rng, n=4000) if g in (0.0, 2.0, 4.0) else None
        rows.append(dict(g=g, var=var, dvar=dvar, ep_omega=epO, ep_Q=epQ, ep_analytic=ep_analytic,
                         sigma_min=sm, amp_factor=amp, ep_sim=(None if eps is None else float(eps)),
                         Q_antisym_relerr=float(np.linalg.norm(Q + Q.T) / max(np.linalg.norm(Q), 1e-30))))
    # gates
    an_ok = all(abs(r["ep_omega"] - r["ep_analytic"]) <= PRE["A_analytic_relerr"] * max(r["ep_analytic"], 1e-12)
                for r in rows)
    sim_rows = [r for r in rows if r["ep_sim"] is not None and r["ep_analytic"] > 1e-9]
    sim_ok = all(abs(r["ep_sim"] - r["ep_analytic"]) <= PRE["A_sim_relerr"] * r["ep_analytic"] for r in sim_rows)
    floor_ok = abs(rows[0]["ep_omega"]) <= PRE["A_floor_zero"]
    epeqvar_ok = all(abs(r["ep_omega"] - r["dvar"]) <= PRE["A_EpEqVar_2x2"] * max(abs(r["ep_omega"]), 1e-12)
                     for r in rows)
    return dict(rows=rows, analytic_matches=an_ok, sim_over_det=sim_ok, floor_is_zero=floor_ok,
                ep_eq_dvar_2x2=epeqvar_ok)


# ============================================================ ANTI-HYPE: Ep==dVar is a units coincidence (time-rescale)
def part_C3_rescale(rng):
    lam = np.array([-1.0, -1.5, -2.0, -2.5]); Nmat = np.triu(rng.standard_normal((4, 4)), 1); g = 2.0
    A0 = make_A(lam, Nmat, g); rows = []
    for c in [0.5, 1.0, 2.0]:
        A = c * A0; S = lyap_sigma(A, np.eye(4)); var = float(np.trace(S))
        dvar = var - normal_ref_var(c * lam); ep = ep_rate(A, S, np.eye(4))
        rows.append(dict(c=c, ep=ep, dvar=dvar, ratio=ep / dvar))
    ratios = np.array([r["ratio"] for r in rows]); cs = np.array([r["c"] for r in rows])
    ratio_span = float(ratios.max() / ratios.min())
    slope_ratio = slope(cs, ratios)                          # == 2 (rate/variance dimensional signature)
    coincidence = bool(ratio_span >= PRE["C3_rescale_ratio_min"]
                       and PRE["C3_rescale_slope"][0] <= slope_ratio <= PRE["C3_rescale_slope"][1])
    return dict(rows=rows, ratio_span=ratio_span, loglog_slope_vs_c=slope_ratio, is_units_coincidence=coincidence)


# ============================================================ PART B -- fixed-spectrum non-normality sweep
def part_B(rng):
    lam = np.array([-1.0, -1.5, -2.0, -2.5]); Nmat = np.triu(rng.standard_normal((4, 4)), 1)
    gs = [0.0, 0.3, 0.6, 1.0, 1.6, 2.4, 3.5]; vnorm = normal_ref_var(lam); rows = []
    for g in gs:
        A = make_A(lam, Nmat, g); ev = np.linalg.eigvals(A)
        S = lyap_sigma(A, np.eye(4)); var = float(np.trace(S)); dvar = var - vnorm
        ep = ep_rate(A, S, np.eye(4)); sm = pseudo_sigmin(A); gap = -float(np.max(ev.real))
        K = kreiss_const(A); G = transient_gmax(A); nrm = float(np.linalg.svd(A, compute_uv=False)[0] / np.max(np.abs(ev)))
        rows.append(dict(g=g, normA_over_rho=nrm, sigma_min=sm, gap=gap, amp_factor=(gap / sm) ** 2,
                         var=var, dvar=dvar, ep=ep, kreiss=K, gmax=G,
                         spectrum_relerr=float(np.max(np.abs(np.sort(ev.real) - np.sort(lam))))))
    nz = [r for r in rows if r["g"] > 0]
    x = np.array([r["gap"] / r["sigma_min"] for r in nz])
    p_ep = slope(x, [r["ep"] for r in nz]); p_dv = slope(x, [r["dvar"] for r in nz])
    p_K = slope(x, [r["kreiss"] for r in nz]); p_G = slope(x, [r["gmax"] for r in nz])
    floor_ok = abs(rows[0]["ep"]) <= PRE["B_floor_zero"]
    mono = all(nz[i]["ep"] < nz[i + 1]["ep"] for i in range(len(nz) - 1))
    ep_growth = nz[-1]["ep"] / max(nz[0]["ep"], 1e-12); k_growth = nz[-1]["kreiss"] / max(nz[0]["kreiss"], 1e-12)
    g_growth = nz[-1]["gmax"] / max(nz[0]["gmax"], 1e-12)
    kreiss_decoupled = bool(ep_growth >= PRE["B_kreiss_decoupled"] * k_growth
                            and ep_growth >= PRE["B_kreiss_decoupled"] * g_growth)
    exp_match = bool(abs(p_ep - p_dv) <= PRE["B_exponent_match_tol"])
    spectrum_fixed = bool(max(r["spectrum_relerr"] for r in rows) < 1e-9)
    return dict(rows=rows, exp_Ep=p_ep, exp_dVar=p_dv, exp_Kreiss=p_K, exp_Gmax=p_G, floor_is_zero=floor_ok,
                monotone=mono, ep_growth=ep_growth, kreiss_growth=k_growth, gmax_growth=g_growth,
                kreiss_decoupled=kreiss_decoupled, exponent_matches=exp_match, spectrum_fixed_exact=spectrum_fixed)


# ============================================================ SCOPE -- is the price an isotropic-noise artifact?
def noise_alignment_scope(rng):
    """ADV-honest-neg strongest form: the 'price' is defined vs ISOTROPIC noise (D1's default/observer metric).
       ROBUST result: aligning the bath to the non-normal geometry (D_eq = V V^T for A=V Lam V^-1) makes the process
       EQUILIBRIUM (Q_eq = A Sig_eq + D_eq = 0 EXACTLY) so Ep -> 0 to machine precision. => the dissipation is the
       energetic price of the noise/geometry MISMATCH (running a non-normal operator through an unaligned/isotropic
       bath -- which IS the D1/default-observer setting), NOT a bath-independent invariant. HONEST: the variance
       magnitude under the aligned bath is scaling-dependent (choice of Tr D_eq), so this cell claims ONLY the
       robust Ep->0 (bath-alignment removes the energy price); it does NOT make a variance verdict here."""
    lam = np.array([-1.0, -1.6, -2.4]); Nmat = np.triu(rng.standard_normal((3, 3)), 1); g = 2.0
    V = np.eye(3) + g * Nmat; A = V @ np.diag(lam) @ np.linalg.inv(V)
    vfloor = normal_ref_var(lam)
    Iso = np.eye(3); Sig_iso = lyap_sigma(A, Iso); ep_iso = ep_rate(A, Sig_iso, Iso); var_iso = float(np.trace(Sig_iso))
    Deq = V @ V.T                                                       # aligned bath (RAW; no rescale -> honest Ep test)
    Sig_eq = lyap_sigma(A, Deq); ep_eq = ep_rate(A, Sig_eq, Deq)
    Q_eq = A @ Sig_eq + Deq
    return dict(g=g, eig_floor_var=vfloor,
                isotropic=dict(D="I", ep=ep_iso, var=var_iso, amplified=bool(var_iso > vfloor + 1e-9)),
                aligned=dict(D="V V^T", ep=ep_eq, ep_is_zero=bool(abs(ep_eq) < 1e-8),
                             Q_eq_norm=float(np.linalg.norm(Q_eq))),
                reading="isotropic bath: Ep=%.3f>0 (energy price) & Var=%.3f amplified vs eig-floor %.3f; aligned "
                        "bath D=VV^T: Q_eq=%.1e=0 => Ep=%.1e~0 (price REMOVED). The dissipation is the noise/geometry "
                        "MISMATCH price (isotropic = D1's default metric); bath-alignment (anisotropic D) removes it. "
                        "Variance magnitude under alignment is scaling-dependent -> no variance verdict claimed."
                        % (ep_iso, var_iso, vfloor, float(np.linalg.norm(Q_eq)), ep_eq))


# ============================================================ PART C1 -- rotation control (complex spectrum)
def part_C1(rng):
    """NORMAL rotation (complex spectrum) dissipates WITHOUT variance amplification; the NON-NORMAL excess over that
       baseline is what tracks the variance excess. Isolates non-normality from the rotation confound. 3x3 (complex
       pair + real eig) so the excess-exponent match is APPROXIMATE (real independence), not the exact 2x2 identity."""
    w0 = 1.3
    An = np.array([[-1.0, w0, 0.0], [-w0, -1.0, 0.0], [0.0, 0.0, -1.5]])  # normal block-diag: eig -1+-i*w0 and -1.5
    Sn = lyap_sigma(An, np.eye(3)); ep_n = ep_rate(An, Sn, np.eye(3)); var_n = float(np.trace(Sn))
    normal_nonnormality = float(np.linalg.norm(An @ An.T - An.T @ An))  # == 0 for normal
    N = np.triu(rng.standard_normal((3, 3)), 1); rows = []             # add non-normality, keep the same spectrum
    for g in [0.0, 0.4, 0.8, 1.4, 2.2]:
        V = np.eye(3) + g * N; A = V @ An @ np.linalg.inv(V); ev = np.linalg.eigvals(A)
        S = lyap_sigma(A, np.eye(3)); var = float(np.trace(S)); ep = ep_rate(A, S, np.eye(3))
        sm = pseudo_sigmin(A); gap = -float(np.max(ev.real))
        rows.append(dict(g=g, ep=ep, var=var, ep_excess=ep - ep_n, var_excess=var - var_n,
                         sigma_min=sm, gap=gap,
                         eig_relerr=float(np.max(np.abs(np.sort_complex(ev) - np.sort_complex(np.linalg.eigvals(An)))))))
    nz = [r for r in rows if r["g"] > 0 and r["ep_excess"] > 0 and r["var_excess"] > 0]
    normal_dissipates = bool(ep_n > PRE["C1_normal_rot_dissipates"])
    # normal rotation variance vs its own eigen-prediction: NOT amplified (variance amplification needs non-normality)
    if len(nz) >= 3:
        xx = np.array([r["gap"] / r["sigma_min"] for r in nz])
        p_ep_ex = slope(xx, [r["ep_excess"] for r in nz]); p_var_ex = slope(xx, [r["var_excess"] for r in nz])
        excess_tracks = bool(abs(p_ep_ex - p_var_ex) <= PRE["C1_excess_tracks"])
    else:
        p_ep_ex = p_var_ex = None; excess_tracks = False
    return dict(normal_ep=ep_n, normal_var=var_n, normal_nonnormality=normal_nonnormality,
                normal_dissipates_without_amp=normal_dissipates, rows=rows,
                exp_ep_excess=p_ep_ex, exp_var_excess=p_var_ex, excess_tracks_variance=excess_tracks)


# ============================================================ PART D -- instance space (exponents co-wander)
def part_D(rng):
    p_eps = []; p_dvs = []; p_Ks = []; n = 0; details = []
    for _ in range(60):
        m = int(rng.integers(3, 6))
        lam = -np.sort(rng.uniform(0.6, 3.0, m))             # distinct real negative spectrum
        Nmat = np.triu(rng.standard_normal((m, m)), 1)
        if np.linalg.norm(Nmat) < 1e-6: continue
        vnorm = normal_ref_var(lam); gs = np.geomspace(0.25, 4.0, 7); xs = []; eps = []; dvs = []; Ks = []; ok = True
        for g in gs:
            A = make_A(lam, Nmat, g); ev = np.linalg.eigvals(A)
            if np.max(ev.real) > -1e-6: ok = False; break
            S = lyap_sigma(A, np.eye(m)); var = float(np.trace(S)); dvar = var - vnorm
            ep = ep_rate(A, S, np.eye(m)); sm = pseudo_sigmin(A, ngrid=801); gap = -float(np.max(ev.real))
            if not (ep > 0 and dvar > 0 and sm > 0): ok = False; break
            xs.append(gap / sm); eps.append(ep); dvs.append(dvar); Ks.append(kreiss_const(A, ne=40, no=41))
        if not ok or len(xs) < 5: continue
        # need a non-degenerate amplification range to fit an exponent
        if (max(xs) / min(xs)) < 1.5: continue
        p_ep = slope(xs, eps); p_dv = slope(xs, dvs); p_K = slope(xs, Ks)
        p_eps.append(p_ep); p_dvs.append(p_dv); p_Ks.append(p_K); n += 1
        details.append(dict(m=m, p_ep=round(p_ep, 3), p_dv=round(p_dv, 3), p_K=round(p_K, 3)))
    p_eps = np.array(p_eps); p_dvs = np.array(p_dvs); p_Ks = np.array(p_Ks)
    match_med = float(np.median(np.abs(p_eps - p_dvs))) if n else None
    wander = float(np.percentile(p_dvs, 95) - np.percentile(p_dvs, 5)) if n else None  # robust spread (not max-min)
    kreiss_mis = float(np.median(np.abs(p_eps - p_Ks))) if n else None
    # Pearson r between the (wandering) Ep and dVar exponents = the 'same governor' signature (r~1 but not identical)
    r_ep_dv = float(np.corrcoef(p_eps, p_dvs)[0, 1]) if n > 2 else None
    r_ep_K = float(np.corrcoef(p_eps, p_Ks)[0, 1]) if n > 2 else None
    return dict(n_instances=n, exp_Ep_median=float(np.median(p_eps)) if n else None,
                exp_dVar_median=float(np.median(p_dvs)) if n else None,
                exp_Kreiss_median=float(np.median(p_Ks)) if n else None,
                median_abs_exp_diff_Ep_dVar=match_med, dVar_exp_wander_p5p95=wander,
                median_abs_exp_diff_Ep_Kreiss=kreiss_mis, corr_Ep_dVar=r_ep_dv, corr_Ep_Kreiss=r_ep_K,
                exp_range=[float(min(p_dvs)), float(max(p_dvs))] if n else None, sample=details[:12])


# ============================================================ Harada-Sasa structural anchor (FDT violation ~ Q)
def harada_sasa_structure(rng):
    """external anchor: dissipation = integrated FDT-violation (Harada-Sasa 2005). For OU: response chi(t)=e^{At},
       correlation C(t)=e^{At}Sigma; FDT-violation V(t)=d/dt C(t) + chi(t) = e^{At}(A Sigma + I) = e^{At} Q.
       => V==0 (FDT holds) IFF Q==0 IFF symmetric/equilibrium; V!=0 (FDT broken) driven by the SAME Q that gives Ep.
       Verified numerically at t=0: V(0)=Q, and Ep=Tr[Q Sigma^-1 Q^T]. Ties fluctuation-amp and dissipation to ONE Q."""
    lam = np.array([-1.0, -1.7, -2.3]); Nmat = np.triu(rng.standard_normal((3, 3)), 1); out = []
    for tag, g in [("symmetric", 0.0), ("nonnormal", 1.8)]:
        A = make_A(lam, Nmat, g); S = lyap_sigma(A, np.eye(3)); Q = A @ S + np.eye(3)
        ts = np.linspace(0, 2.0, 25)
        Vnorm = float(np.trapezoid([np.linalg.norm(expm(A * t) @ Q) for t in ts], ts))   # integrated FDT-violation
        ep, _ = ep_rate_Q(A, S, np.eye(3))
        out.append(dict(case=tag, g=g, Q_norm=float(np.linalg.norm(Q)),
                        fdt_holds=bool(np.linalg.norm(Q) < 1e-9), fdt_violation_integral=Vnorm, ep=ep))
    return out


# ============================================================ main
def main():
    rng = np.random.default_rng(PRE["SEED"])
    print("=" * 112)
    print("NON-NORMALITY'S THERMODYNAMIC PRICE -- does the pseudospectral variance-amplification cost EXCESS DISSIPATION?")
    print("=" * 112)

    A = part_A(np.random.default_rng(PRE["SEED"] + 1))
    C3 = part_C3_rescale(np.random.default_rng(PRE["SEED"] + 2))
    B = part_B(np.random.default_rng(PRE["SEED"] + 3))
    C1 = part_C1(np.random.default_rng(PRE["SEED"] + 4))
    D = part_D(np.random.default_rng(PRE["SEED"] + 5))
    HS = harada_sasa_structure(np.random.default_rng(PRE["SEED"] + 6))
    NA = noise_alignment_scope(np.random.default_rng(PRE["SEED"] + 7))

    print("\n[A] 2x2 defective (eig both -1, gap=1), D=I.  Ep_closed==Ep_Q==g^2/2==dVar; 3rd route=Sekimoto sim")
    print("   g   |  Var  dVar |  Ep_Om  Ep_Q  Ep(g^2/2) | Ep_sim(indep) | sigma_min amp=(1/sm)^2")
    for r in A["rows"]:
        print("  %.1f | %5.2f %5.2f | %6.3f %6.3f %8.3f | %13s | %.4f   %6.2f" % (
            r["g"], r["var"], r["dvar"], r["ep_omega"], r["ep_Q"], r["ep_analytic"],
            ("%.4f" % r["ep_sim"]) if r["ep_sim"] is not None else "     -", r["sigma_min"], r["amp_factor"]))
    print("   analytic-match=%s  Sekimoto-sim-over-det=%s  reversible-floor(sym)=0:%s  Ep==dVar(2x2 defective)=%s"
          % (A["analytic_matches"], A["sim_over_det"], A["floor_is_zero"], A["ep_eq_dvar_2x2"]))

    print("\n[ANTI-HYPE C3] is Ep==dVar a THEOREM or a units coincidence? time-rescale A->c*A:")
    for r in C3["rows"]:
        print("   c=%.1f  Ep=%.4f  dVar=%.4f  Ep/dVar=%.4f" % (r["c"], r["ep"], r["dvar"], r["ratio"]))
    print("   Ep/dVar span=%.2fx (>=%.1f) loglog-slope-vs-c=%.3f (==2 rate/variance sig) -> UNITS COINCIDENCE=%s"
          % (C3["ratio_span"], PRE["C3_rescale_ratio_min"], C3["loglog_slope_vs_c"], C3["is_units_coincidence"]))

    print("\n[B] fixed real spectrum lam=[-1,-1.5,-2,-2.5], vary non-normality g (spectrum fixed exact=%s):"
          % B["spectrum_fixed_exact"])
    print("   g   ||A||/rho sigma_min amp=(gap/sm)^2  Var  dVar   Ep     KreissK  G_max(transient)")
    for r in B["rows"]:
        print("  %.1f   %6.2f   %.4f   %8.2f  %6.3f %6.3f %6.3f  %6.3f   %6.3f" % (
            r["g"], r["normA_over_rho"], r["sigma_min"], r["amp_factor"], r["var"], r["dvar"], r["ep"],
            r["kreiss"], r["gmax"]))
    print("   EXPONENTS vs (gap/sigma_min):  Ep~^%.3f  dVar~^%.3f  Kreiss~^%.3f  G_max~^%.3f"
          % (B["exp_Ep"], B["exp_dVar"], B["exp_Kreiss"], B["exp_Gmax"]))
    print("   floor(g=0)=0:%s  Ep-monotone:%s  Ep/dVar co-track(|dexp|<=%.2f):%s  transient-decoupled(Ep %.0fx vs K %.1fx, Gmax %.1fx):%s"
          % (B["floor_is_zero"], B["monotone"], PRE["B_exponent_match_tol"], B["exponent_matches"],
             B["ep_growth"], B["kreiss_growth"], B["gmax_growth"], B["kreiss_decoupled"]))

    print("\n[C1 rotation control] NORMAL complex-spectrum baseline (eig -1+-1.3i):")
    print("   normal Ep=%.4f (>0: rotation dissipates) with nonnormality-defect=%.1e (==0 normal); Var=%.3f (NOT amp'd)"
          % (C1["normal_ep"], C1["normal_nonnormality"], C1["normal_var"]))
    print("   non-normal EXCESS over the rotation baseline: exp(Ep_excess)=%s  exp(Var_excess)=%s  co-track=%s"
          % (C1["exp_ep_excess"], C1["exp_var_excess"], C1["excess_tracks_variance"]))

    print("\n[D instance space] random fixed-spectrum non-normal families (%d):" % D["n_instances"])
    print("   median exponent  Ep~^%.3f  dVar~^%.3f  Kreiss~^%.3f   (dVar exponent RANGE across families=%s)" % (
        D["exp_Ep_median"] or 0, D["exp_dVar_median"] or 0, D["exp_Kreiss_median"] or 0,
        [round(v, 2) for v in (D["exp_range"] or [0, 0])]))
    print("   Ep/dVar co-track: median|dexp|=%.3f (<=%.2f), corr r=%.4f | dVar exp WANDERS p5-p95=%.3f (>=%.2f, "
          "model-specific) | Ep-vs-Kreiss mismatch |dexp|=%.3f (>=%.2f), corr r=%.3f" % (
        D["median_abs_exp_diff_Ep_dVar"] or 0, PRE["D_exp_match_med_tol"], D["corr_Ep_dVar"] or 0,
        D["dVar_exp_wander_p5p95"] or 0, PRE["D_exp_wander_min"], D["median_abs_exp_diff_Ep_Kreiss"] or 0,
        PRE["D_kreiss_mismatch_min"], D["corr_Ep_Kreiss"] or 0))

    print("\n[ANCHOR Harada-Sasa] dissipation = integrated FDT-violation; violation V(t)=e^{At}Q driven by the SAME Q:")
    for h in HS:
        print("   %-10s g=%.1f  ||Q||=%.4f  FDT-holds=%s  FDT-violation-integral=%.4f  Ep=%.4f" % (
            h["case"], h["g"], h["Q_norm"], h["fdt_holds"], h["fdt_violation_integral"], h["ep"]))

    print("\n[SCOPE noise-alignment] is the price an ISOTROPIC-noise artifact? (eig-floor Var=%.3f)" % NA["eig_floor_var"])
    print("   isotropic bath D=I  : Ep=%.4f (>0, PRICE)   Var=%.3f (amplified vs floor=%s)"
          % (NA["isotropic"]["ep"], NA["isotropic"]["var"], NA["isotropic"]["amplified"]))
    print("   aligned  bath D=VV^T: Q_eq=%.1e (=0 -> equilibrium)  Ep=%.2e (~0, price REMOVED=%s)"
          % (NA["aligned"]["Q_eq_norm"], NA["aligned"]["ep"], NA["aligned"]["ep_is_zero"]))
    print("   -> the ENERGY price is the noise/geometry MISMATCH (isotropic = D1's default/observer metric);")
    print("      bath-alignment removes the dissipation. So the price is REAL but SCOPED to the (D1) isotropic bath.")

    # ---- gate ----
    A_ok = bool(A["analytic_matches"] and A["sim_over_det"] and A["floor_is_zero"] and A["ep_eq_dvar_2x2"])
    C3_ok = bool(C3["is_units_coincidence"])
    B_ok = bool(B["floor_is_zero"] and B["monotone"] and B["exponent_matches"] and B["kreiss_decoupled"]
                and B["spectrum_fixed_exact"])
    C1_ok = bool(C1["normal_dissipates_without_amp"] and C1["excess_tracks_variance"])
    D_ok = bool(D["n_instances"] >= PRE["D_min_instances"]
                and (D["median_abs_exp_diff_Ep_dVar"] or 9) <= PRE["D_exp_match_med_tol"]
                and (D["dVar_exp_wander_p5p95"] or 0) >= PRE["D_exp_wander_min"]
                and (D["median_abs_exp_diff_Ep_Kreiss"] or 0) >= PRE["D_kreiss_mismatch_min"]
                and (D["corr_Ep_dVar"] or 0) >= 0.9)
    HS_ok = bool(HS[0]["fdt_holds"] and HS[0]["ep"] < 1e-9 and (not HS[1]["fdt_holds"]) and HS[1]["ep"] > 1e-6)

    gates = {"A_analytic+Sekimoto-overdet+zero-floor": A_ok, "C3_EpEqVar_is_units_coincidence": C3_ok,
             "B_sweep_cotrack_sigmamin_not_kreiss": B_ok, "C1_rotation_control": C1_ok,
             "D_instance_exponents_cowander": D_ok, "HS_dissipation_is_FDT_violation": HS_ok}
    print("\n" + "=" * 112)
    for k, v in gates.items():
        print("  [%s] %s" % ("PASS" if v else "FAIL", k))

    qualitative_C = bool(A_ok and B_ok and C1_ok and D_ok and HS_ok)   # governor law
    antihype_bound = bool(C3_ok)                                        # NOT the numerical factor
    verdict = (
        "C (QUALITATIVE governor law) HOLDS + ANTI-HYPE bound HOLDS. Non-normality has a POSITIVE thermodynamic "
        "price: at FIXED spectrum the steady-state dissipation (Sekimoto entropy-production rate) rises from the "
        "reversible/equilibrium FLOOR of exactly 0 (symmetric, same spectrum) and is GOVERNED by the pseudospectral "
        "sigma_min -- the SAME governor as the D1 fluctuation amplification (Ep and dVar co-track with matching, "
        "model-specific exponents %.2f~%.2f that WANDER together across the instance-space; NEITHER tracks the "
        "Kreiss/transient constant). Geometric root: BOTH are generated by the single antisymmetric current matrix "
        "Q=A*Sigma+I, which =0 iff normal-in-the-noise-metric iff equilibrium (Harada-Sasa: dissipation = the FDT "
        "violation, itself proportional to Q). So the D1 amplification is NOT free -- it is the fluctuation face of a "
        "broken detailed balance whose energetic face is the excess dissipation. BUT (anti-hype) the price is NOT "
        "'= the amplification factor': the clean Ep==dVar identity is a UNITS COINCIDENCE (breaks under time-rescale, "
        "Ep/dVar~c^2, span %.1fx), and the prefactor is model-specific. => non-normality's thermodynamic cost is "
        "sigma_min-GOVERNED (universal) but not sigma_min-FACTORED (model-specific)."
        % (B["exp_Ep"], B["exp_dVar"], C3["ratio_span"])
    ) if (qualitative_C and antihype_bound) else \
        "INCONCLUSIVE / partial -- inspect gates (a forced leg did not converge)"

    print("\n  QUALITATIVE governor-law C =", qualitative_C, "| ANTI-HYPE 'not the factor' bound =", antihype_bound)
    print("  VERDICT:", verdict)

    payload = dict(cell="d_nonnormal_thermo_price_of_amplification_probe", prereg=PRE,
                   part_A_2x2_anchor=A, part_C3_units_coincidence=C3, part_B_sweep=B, part_C1_rotation_control=C1,
                   part_D_instance_space=D, anchor_harada_sasa=HS, scope_noise_alignment=NA, gates=gates,
                   qualitative_governor_C=qualitative_C, antihype_not_the_factor=antihype_bound, verdict=verdict,
                   anchors=dict(pseudospectra="sigma_min(i w I - A) distance-to-instability (Trefethen-Embree 2005)",
                                harada_sasa="dissipation = integrated FDT-violation (Harada-Sasa PRL 2005); V(t)=e^{At}Q",
                                analytic_2x2="Ep = g^2/2 = dVar for A=[[-1,g],[0,-1]] (hand-derived, closed form)",
                                units="kT_eff = 1 (star1; D non-eq rig d_noneq_jarzynski_crooks_tur_certwork.py)"))
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w") as fh:
        json.dump(payload, fh, indent=1, default=float)
    print("[EMIT]", os.path.relpath(OUT, ROOT))
    print("=" * 112)
    return 0


if __name__ == "__main__":
    sys.exit(main())
